### ISSUE TITLE
Bot Registration/Signup

### ISSUE THREAD

**Issue by bilby91** [OfficeDev/Microsoft-teams-docs#193]
Hello,

I’m in the process of building a bot for MS Teams. I have previous experience doing this with Slack and Slack provides a custom button or link that I can share with anyone so that they can install my bot.

Is this possible using MS Teams ? I know that I can submit my application to the Office Store but from a marketing perspective we want to be able to allow the user to install it from an action in our website. If this is even possible, how can I get informed when the user has installed my bot in his account/team ? Is there any callback I get when that happens ? Maybe some redirection like the Slack oAuth process ?

Thanks a lot!

**Comment by RichMoeMSFT** [comment]
Just [updated documentation](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd#adding-a-bot-for-11-chat-only) on this in fact (3rd option).

Right now, you can deeplink to a 1:1 bot only, using the bot's app id.  This means while you can provide access for your users to install, it will only be in 1:1 context - cannot be added to a team, nor use any of the other Microsoft Teams app capabilities like tabs, etc.

When you add it, you will get a `conversationUpdate` message but of course the Teams channel data won't be included (since it's not in a team.)

Currently, a bot has to go through our one of our app installation processes to be available in team channels, which means you'd have to:
1) Create a proper manifest
2) Build it into a Microsoft Teams app package and
3) Install via sideloading, or submit to and acquire from the Office Store.

Hope this helps.

**Comment by bilby91** [comment]
@RichMoeMSFT 👌

I think it would be great if you could install the bot (for your team) without going through the Office Store but I guess that can be a feature request.

Thanks!
