### ISSUE TITLE
heroImage section not rendering in Teams

### ISSUE THREAD

**Issue by anthu** [OfficeDev/Microsoft-teams-docs#202]
HeroImage is not rendering for me in Teams. It's simply ommited in the card.

For example sending the Twitter heroImage example from CardPlayground to a Teams channel via REST only shows the text sections.

Is there any updated schema documentation available?

**Comment by RichMoeMSFT** [comment]
@anthu Apologies for the delay:  I'm checking with engineering on this.  We have O365 connector card support in our C# Botbuilder Teams extension SDK (coming soon for Node.js) and we don't support it through there yet...

**Comment by majordamage** [comment]
Most likely, the issue is the size of the image: A card image is limited to 1024×1024 pixels; the image in the example is 1200×800.

This limitation (and a smaller maximum file size of 1 MB) is now documented in https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages.

Thanks for your feedback!
